#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "${SCRIPT}")

DOCKER_DIR=$(readlink -f "${SCRIPT_DIR}/..")
COMPOSE_FILE=${DOCKER_DIR}/docker-compose.yml


usage() {
    echo "Docker4c - container for C/C++ development"
    echo "Usage: $0 <command> [<args>]"
    echo ""
    echo "Commands:"
    echo "  build     - build the container"  
    echo "  up        - starts the container"
    echo "  down      - stops and removes the container"
    echo "  run       - open a shell in the container"
    echo "  run <cmd> - run <cmd> inside the container"
    exit 0
}


_compose() {
    docker-compose -f "$COMPOSE_FILE" "$@"
}

_container() {
    _compose ps -q
}

_is_up() {
    CONTAINER=$(_container)
    test -n "$CONTAINER" && docker ps -q --no-trunc | grep "$CONTAINER" > /dev/null
    return $?
}

docker4c_up() {
    _compose up -d
}

docker4c_down() {
    _compose down
}

docker4c_build() {
    _is_up && docker4c_down
    DOCKER_BUILDKIT=1 docker build -t cppenv:latest "$DOCKER_DIR"
}

docker4c_run() {
    _is_up || docker4c_up
    WORKDIR=$(pwd | sed "s#${HOME}#/home/dev#")

    if [ $# -ne 0 ]; then
        # (The shell is interactive if run is called without)
        docker exec -i -t -u dev:dev $(_container) bash -c "if [ -d \"${WORKDIR}\" ]; then cd ${WORKDIR}; fi; ${*@Q}"
    else
        docker exec -i -t -u dev:dev $(_container) bash -c "if [ -d \"${WORKDIR}\" ]; then cd ${WORKDIR}; fi; bash"
    fi
}


[ -n "$1" ] || usage
COMMAND=$1
shift

case ${COMMAND} in
    up)
        docker4c_up
        ;;
    down)
        docker4c_down
        ;;
    build)
        docker4c_build
        ;;
    run)
        docker4c_run "$@"    
        ;;
    *)
        usage
        ;;
esac


