name: Create and publish the Docker4c images

on: 
  push:
    branches:
      - 'master'
      - 'feature/*'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up builder for ci image
        uses: docker/setup-buildx-action@v1
        id: builder-ci
      
      - name: Set up builder for dev image
        uses: docker/setup-buildx-action@v1
        id: builder-dev

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build ci image
        id: ci_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-ci.outputs.name }}
          context: .
          target: cpp_ci_image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false

      - name: Build dev image
        id: dev_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-dev.outputs.name }}
          context: .
          target: cpp_dev_image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false

      - name: Image digest
        run: echo ${{ steps.ci_build.outputs.digest }} ${{ steps.dev_build.outputs.digest }}